# ./docker-compose.yml
version: '3'

services:
  node:
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    container_name: node-app
    volumes:
      - .:/usr/src/app
    ports:
      - "8088:8080"